python_version: "3.10"
venv_directory: .venv
environments:
  dev:
    requirements:
      - import: requirements.dev.txt

  ci:
    requirements:
      - import: requirements.ci.txt

requirements:
  - import: requirements.txt
